services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  proxy:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${HTTP_PORT:-3128}:${HTTP_PORT:-3128}"
      - "${SOCKS_PORT:-1080}:${SOCKS_PORT:-1080}"
      - "${HTTPS_PORT:-8443}:${HTTPS_PORT:-8443}"
    volumes:
      - ./3proxy:/assets:ro
      - ./logs:/var/log/3proxy
    restart: unless-stopped

volumes:
  pgdata:
